import { NextApiRequest, NextApiResponse } from 'next';

const successResponse = {
     apiMerchantId: '6008138000',
     paymentSystem: 'Teb test ps',
     pgTranDate: '20141215 17:22:54',
     merchantPaymentId: 'session-a7bAS3AddR5PApN',
     pgTranId: '14349RW4Q89120700',
     pgTranRefId: '4398417187960',
     pgOrderId: 'session-a7bRkDJK091pN',
     responseCode: '00',
     responseMsg: 'Approved',
};

const coreErrorCodes = [
     { errorCode: 'ERR10010', errorMessage: 'Required but null parameter.' },
     { errorCode: 'ERR10011', errorMessage: 'Multi - definition for the same parameter.' },
     { errorCode: 'ERR10012', errorMessage: 'Maximum length exceeded for data' },
     { errorCode: 'ERR10013', errorMessage: 'Data type is not valid' },
     { errorCode: 'ERR10014', errorMessage: 'Security algorithm could not be found' },
     { errorCode: 'ERR10015', errorMessage: 'Invalid merchant' },
     { errorCode: 'ERR10016', errorMessage: 'Invalid amount' },
     { errorCode: 'ERR10017', errorMessage: 'Invalid currency' },
     { errorCode: 'ERR10018', errorMessage: 'Invalid language' },
     { errorCode: 'ERR10019', errorMessage: 'General error' },
     { errorCode: 'ERR10020', errorMessage: 'The user is not authenticated' },
     { errorCode: 'ERR10021', errorMessage: 'Parameter is empty' },
     { errorCode: 'ERR10022', errorMessage: 'Items total amount does not match items sum' },
     { errorCode: 'ERR10023', errorMessage: 'Payment amount does not match calculated valueERR10024 Tax amount not specified' },
     { errorCode: 'ERR10025', errorMessage: 'Tax amount should be zero' },
     { errorCode: 'ERR10026', errorMessage: 'Invalid integration model supplied' },
     { errorCode: 'ERR10027', errorMessage: 'Invalid card token provided' },
     { errorCode: 'ERR10028', errorMessage: 'Payment system not found' },
     { errorCode: 'ERR10029', errorMessage: 'Payment type not found' },
     { errorCode: 'ERR10030', errorMessage: 'Transaction not found' },
     { errorCode: 'ERR10031', errorMessage: 'Transaction not refundable' },
     { errorCode: 'ERR10032', errorMessage: 'Invalid refund amount' },
     { errorCode: 'ERR10033', errorMessage: 'Transaction cannot be voided' },
     { errorCode: 'ERR10034', errorMessage: 'Payment not found' },
     { errorCode: 'ERR10035', errorMessage: 'No PREAUTH transaction for payment' },
     { errorCode: 'ERR10036', errorMessage: 'Invalid POSTAUTH amount' },
     { errorCode: 'ERR10037', errorMessage: 'Cardholder does not exist' },
     { errorCode: 'ERR10038', errorMessage: 'There is no payment waiting for confirmation' },
     { errorCode: 'ERR10039', errorMessage: 'Invalid payment status' },
     { errorCode: 'ERR10040', errorMessage: 'Invalid subaction' },
     { errorCode: 'ERR10041', errorMessage: 'Card already exists' },
     { errorCode: 'ERR10042', errorMessage: 'This Card is removed' },
     { errorCode: 'ERR10043', errorMessage: 'Invalid period provided' },
     { errorCode: 'ERR10044', errorMessage: 'Invalid date format' },
     { errorCode: 'ERR10045', errorMessage: 'Invalid PAN number' },
     { errorCode: 'ERR10046', errorMessage: 'Invalid expiry date' },
     { errorCode: 'ERR10047', errorMessage: 'User not authorized to make API calls' },
     { errorCode: 'ERR10048', errorMessage: 'Merchant Payment ID already exists' },
     { errorCode: 'ERR10049', errorMessage: 'Invalid Merchant Group ID' },
     { errorCode: 'ERR10050', errorMessage: 'Invalid hash value' },
     { errorCode: 'ERR10051', errorMessage: 'No payment systems.Please make sure that you have at least one payment system.' },
     { errorCode: 'ERR10052', errorMessage: 'Unsupported merchant currency' },
     { errorCode: 'ERR10053', errorMessage: 'User not authorized for this merchant' },
     { errorCode: 'ERR10054', errorMessage: 'Payment expiry time exceeds maximum limit' },
     { errorCode: 'ERR10055', errorMessage: 'Payment expiry time is less than the minimal limit' },
     { errorCode: 'ERR10056', errorMessage: 'Invalid API action' },
     { errorCode: 'ERR10057', errorMessage: 'Card Bin does not exist' },
     { errorCode: 'ERR10058', errorMessage: 'Card already activated' },
     { errorCode: 'ERR10059', errorMessage: 'Card already deactivated' },
     { errorCode: 'ERR10060', errorMessage: 'Invalid user IP address' },
     { errorCode: 'ERR10061', errorMessage: 'Invalid Response Format' },
     { errorCode: 'ERR10062', errorMessage: 'Card not yet activated' },
     { errorCode: 'ERR10063', errorMessage: 'This action is available only for LetsBodrum cards' },
     { errorCode: 'ERR10064', errorMessage: 'Please use a LetsBodrum card or an bank credit card' },
     { errorCode: 'ERR10065', errorMessage: 'PAN number already exits' },
     { errorCode: 'ERR10066', errorMessage: 'Inconsistent Date' },
     { errorCode: 'ERR10067', errorMessage: 'Invalid recurring plan code' },
     { errorCode: 'ERR10068', errorMessage: 'Invalid Occurance parametar' },
     { errorCode: 'ERR10069', errorMessage: 'Quartz error' },
     { errorCode: 'ERR10070', errorMessage: 'Start date should be after now' },
     { errorCode: 'ERR10071', errorMessage: 'Invalid Recurring Payment status parameter' },
     { errorCode: 'ERR10072', errorMessage: 'Recurring plan already active' },
     { errorCode: 'ERR10073', errorMessage: 'Recurring plan already inactive' },
     { errorCode: 'ERR10074', errorMessage: 'Recurring plan already expired' },
     { errorCode: 'ERR10075', errorMessage: 'Logo Error' },
     { errorCode: 'ERR10076', errorMessage: 'Invalid Recurring Plan status parameter' },
     { errorCode: 'ERR10077', errorMessage: 'Invalid template' },
     { errorCode: 'ERR10078', errorMessage: 'Transaction is locked' },
     { errorCode: 'ERR10079', errorMessage: 'This card is already saved by different customer' },
     { errorCode: 'ERR10080', errorMessage: 'Please provide Merchant Payment Id or Payment Token' },
     { errorCode: 'ERR10081', errorMessage: 'Invalid Transaction Type' },
     { errorCode: 'ERR10082', errorMessage: 'The user has no permission to perform this API action' },
     { errorCode: 'ERR10083', errorMessage: 'Invalid Status' },
     { errorCode: 'ERR10084', errorMessage: 'Interest or discount rate must be zero' },
     { errorCode: 'ERR10085', errorMessage: 'Current end date can not be greater than current start date' },
     { errorCode: 'ERR10086', errorMessage: 'The current end date must be greater than the current date' },
     { errorCode: 'ERR10087', errorMessage: 'The installment number already has a payment type with this payment system' },
     { errorCode: 'ERR10088', errorMessage: 'The installment should be 1 - 12' },
     { errorCode: 'ERR10090', errorMessage: 'Action Failed' },
     { errorCode: 'ERR10091', errorMessage: 'Can not process because payment system is disabled.Please contact the Super Admin' },
     { errorCode: 'ERR10092', errorMessage: 'Invalid Offset Value' },
     { errorCode: 'ERR10093', errorMessage: 'Invalid Limit' },
     { errorCode: 'ERR10094', errorMessage: 'A defined card was not found' },
     { errorCode: 'ERR10095', errorMessage: 'The card can not be deleted due to the recurring payment plans that are registered' },
     { errorCode: 'ERR10096', errorMessage: 'Invalid session information.' },
     { errorCode: 'ERR10097', errorMessage: 'Terminated session information.' },
     { errorCode: 'ERR10098', errorMessage: 'This session key does not have the authorization to process.' },
     { errorCode: 'ERR10099', errorMessage: 'This process belongs to another member business.' },
     { errorCode: 'ERR10100', errorMessage: 'There are multiple successful transactions for this payment, please use the PGTRANID parameter.' },
     { errorCode: 'ERR10101', errorMessage: 'Please send the POST request in the method body.Parameters sent in Query String are not safe.' },
     { errorCode: 'ERR10102', errorMessage: 'Invalid BIN value' },
     { errorCode: 'ERR10103', errorMessage: 'The transaction request was rejected because of the fraud probability reported by the Inact RT service.' },
     { errorCode: 'ERR10104', errorMessage: 'Invalid card information' },
     { errorCode: 'ERR10106', errorMessage: 'This payment has already been made, and a new payment session can not be created with the given Member Place Order Number.' },
     { errorCode: 'ERR10107', errorMessage: 'The used payment system does not support the campaign code.' },
     { errorCode: 'ERR10108', errorMessage: 'Score usage is not supported by the payment system' },
     { errorCode: 'ERR10109', errorMessage: 'This merchantpaymentId is used before and its session expired; please use different merchantPaymentId' },
     { errorCode: 'ERR10110', errorMessage: 'The request does not match one of the session value, exchange rate, session type, URL value, or transaction value for the current order number' },
     { errorCode: 'ERR10111', errorMessage: 'The point question is not supported by this payment system' },
     { errorCode: 'ERR10112', errorMessage: 'Score json form is invalid' },
     { errorCode: 'ERR10113', errorMessage: 'No recurring payments found' },
     { errorCode: 'ERR10114', errorMessage: 'Recurring payment plan status COMPLETED can not be changed' },
     { errorCode: 'ERR10115', errorMessage: 'The number of repetitions must be between 1 and 99' },
     { errorCode: 'ERR10116', errorMessage: 'Recurring payment plan code available' },
     { errorCode: 'ERR10117', errorMessage: 'Pre - authorizing wallet sessions should not contain order numbers' },
     { errorCode: 'ERR10119', errorMessage: 'The is incorrect payment system score parameter and the score parameter sent in the payment system to which the transaction is to be sent is not defined.' },
     { errorCode: 'ERR10120', errorMessage: 'Points can not be blank' },
     { errorCode: 'ERR10121', errorMessage: 'Use of fractional points is not supported by this payment system' },
     { errorCode: 'ERR10122', errorMessage: 'The number for the repeat frequency is D for the day, M for the month, Y for the year; eg 7D for 7 days, 1M per month, 1Y per year.' },
     { errorCode: 'ERR10123', errorMessage: 'No Wanted BKM Transaction found' },
     { errorCode: 'ERR10124', errorMessage: 'The transaction for the specified token was found.' },
     { errorCode: 'ERR10125', errorMessage: 'The requested operation can not be updated.' },
     { errorCode: 'ERR10126', errorMessage: 'Payment System Type or EFT code is required if BIN is not given' },
     { errorCode: 'ERR10127', errorMessage: 'Invalid extra parameter value specified' },
     { errorCode: 'ERR10128', errorMessage: 'The recurring payment plan has one or more processed transactions and tgerefore can not be deleted.' },
     { errorCode: 'ERR10129', errorMessage: 'Payment System Not Updated' },
     { errorCode: 'ERR10130', errorMessage: 'The name given for the payment system is in use' },
     { errorCode: 'ERR10131', errorMessage: 'Payment system type available' },
     { errorCode: 'ERR10132', errorMessage: 'Connection Error / Incorrect Data' },
     { errorCode: 'ERR10133', errorMessage: 'This item has been deprecated.Items that are deprecated can not be updated.' },
     { errorCode: 'ERR10134', errorMessage: 'Since the payment system is out of use, it can not be accepted as default.Please enable it first.' },
     { errorCode: 'ERR10135', errorMessage: 'You can not deactivate a payment system marked as default.Please mark another payment system as default first.' },
     { errorCode: 'ERR10136', errorMessage: 'Invalid Request parameter' },
     { errorCode: 'ERR10137', errorMessage: 'Paid or CANCELED payment.' },
     { errorCode: 'ERR10138', errorMessage: 'Customer not found' },
     { errorCode: 'ERR10139', errorMessage: 'The cardholder identification number must contain 11 numbers' },
     { errorCode: 'ERR10140', errorMessage: 'The campaign questionnaire is not supported by the used payment system.' },
     { errorCode: 'ERR10141', errorMessage: 'Invalid Tags Form.' },
     { errorCode: 'ERR10142', errorMessage: 'The sum of the recurring amounts does not equal the total amount of the recurring payment plan.' },
     { errorCode: 'ERR10143', errorMessage: 'Recurring payment - card bond not found' },
     { errorCode: 'ERR10144', errorMessage: 'Invalid campaign format.' },
     { errorCode: 'ERR10145', errorMessage: 'Recurrent Payment Status can only be Manually Paid updated' },
     { errorCode: 'ERR10146', errorMessage: 'Can not update Recurring Payment Status' },
     { errorCode: 'ERR10147', errorMessage: 'Recurring Payment not found' },
     { errorCode: 'ERR10148', errorMessage: 'Recurring plan status can only be Active or Inactive(Passive)' },
     { errorCode: 'ERR10149', errorMessage: 'Can not be activated if there are no Recurring Plan cards' },
     { errorCode: 'ERR10150', errorMessage: 'In order to update the Recurring Payment Schedule or any Recurring Payment information, you first need to update the Recurring Payment Plan status.' },
     { errorCode: 'ERR10151', errorMessage: 'The request is not in line with the transaction rules.' },
     { errorCode: 'ERR10152', errorMessage: 'Payment Type should apply to at least one Credit / Debit Cards or Business Cards' },
     { errorCode: 'ERR10153', errorMessage: 'Repeat count must be greater than zero' },
     { errorCode: 'ERR10154', errorMessage: 'This can not be done without 3D verification' },
     { errorCode: 'ERR10155', errorMessage: 'You can enable or disable only the merchants that are on the same group' },
     { errorCode: 'ERR10156', errorMessage: 'The specified payment rule was not found' },
     { errorCode: 'ERR10157', errorMessage: 'Specified vendor not found' },
     { errorCode: 'ERR10158', errorMessage: 'A reseller with this code information is available.' },
     { errorCode: 'ERR10159', errorMessage: 'Dealer is disabled, cannot perform action.Please contact your Super Admins' },
]

const vPosErrorCodes = [
     { errorCode: 'ERR20001', errorMessage: 'Referral - call bank for manual approval.' },
     { errorCode: 'ERR20002', errorMessage: 'Fake Approval, but should not be used in a VPOS system, check with your bank.' },
     { errorCode: 'ERR20003', errorMessage: 'Invalid merchant or service provider.' },
     { errorCode: 'ERR20004', errorMessage: 'Pick - up card.' },
     { errorCode: 'ERR20005', errorMessage: 'Do not honour' },
     { errorCode: 'ERR20006', errorMessage: 'Error(found only in file update responses).' },
     { errorCode: 'ERR20007', errorMessage: 'Pick up card, special condition.' },
     { errorCode: 'ERR20008', errorMessage: 'Fake Approval, but should not be used in a VPOS system, check with your bank.' },
     { errorCode: 'ERR20011', errorMessage: 'Fake Approved(VIP), but should not be used in a VPOS system, check with your bank.' },
     { errorCode: 'ERR20012', errorMessage: 'Transaction is not valid.' },
     { errorCode: 'ERR20013', errorMessage: 'Invalid amount.' },
     { errorCode: 'ERR20014', errorMessage: 'Invalid account number.' },
     { errorCode: 'ERR20015', errorMessage: 'No such issuer.' },
     { errorCode: 'ERR20019', errorMessage: 'Reenter, try again.' },
     { errorCode: 'ERR20020', errorMessage: 'Invalid amount.' },
     { errorCode: 'ERR20021', errorMessage: 'Unable to back out transaction.' },
     { errorCode: 'ERR20025', errorMessage: 'Unable to locate record on file.' },
     { errorCode: 'ERR20026', errorMessage: 'Transaction not found' },
     { errorCode: 'ERR20027', errorMessage: 'Bank decline' },
     { errorCode: 'ERR20028', errorMessage: 'Original is denied' },
     { errorCode: 'ERR20029', errorMessage: 'Original not found' },
     { errorCode: 'ERR20030', errorMessage: 'Format error(switch generated)' },
     { errorCode: 'ERR20032', errorMessage: 'Referral(General)' },
     { errorCode: 'ERR20033', errorMessage: 'Expired card, pick - up' },
     { errorCode: 'ERR20034', errorMessage: 'Suspected fraud, pick - up' },
     { errorCode: 'ERR20036', errorMessage: 'Restricted card, pick - up' },
     { errorCode: 'ERR20037', errorMessage: 'Pick up card.Issuer wants card returned' },
     { errorCode: 'ERR20038', errorMessage: 'Allowable PIN tries exceeded, pick - up' },
     { errorCode: 'ERR20041', errorMessage: 'Lost card, pick - up' },
     { errorCode: 'ERR20043', errorMessage: 'Stolen card, pick - up' },
     { errorCode: 'ERR20051', errorMessage: 'Insufficient funds' },
     { errorCode: 'ERR20052', errorMessage: 'No checking account' },
     { errorCode: 'ERR20053', errorMessage: 'No savings account' },
     { errorCode: 'ERR20054', errorMessage: 'Expired card.' },
     { errorCode: 'ERR20055', errorMessage: 'Incorrect PIN' },
     { errorCode: 'ERR20056', errorMessage: 'No card record' },
     { errorCode: 'ERR20057', errorMessage: 'Transaction not permitted to cardholder' },
     { errorCode: 'ERR20058', errorMessage: 'Transaction not permitted to terminal' },
     { errorCode: 'ERR20059', errorMessage: 'Fraud' },
     { errorCode: 'ERR20061', errorMessage: 'Activity amount limit exceeded' },
     { errorCode: 'ERR20062', errorMessage: 'Restricted card' },
     { errorCode: 'ERR20063', errorMessage: 'Security violation' },
     { errorCode: 'ERR20065', errorMessage: 'Activity limit exceeded' },
     { errorCode: 'ERR20075', errorMessage: 'Allowable number of PIN tries exceeded' },
     { errorCode: 'ERR20076', errorMessage: 'Key synchronization error' },
     { errorCode: 'ERR20077', errorMessage: 'Inconsistent data' },
     { errorCode: 'ERR20080', errorMessage: 'Date is not valid' },
     { errorCode: 'ERR20081', errorMessage: 'Encryption Error' },
     { errorCode: 'ERR20082', errorMessage: 'CVV Failure or CVV Value supplied is not valid' },
     { errorCode: 'ERR20083', errorMessage: 'Cannot verify PIN' },
     { errorCode: 'ERR20084', errorMessage: 'Invalid CVV.' },
     { errorCode: 'ERR20085', errorMessage: 'Declined(General)' },
     { errorCode: 'ERR20091', errorMessage: 'Issuer or switch is inoperative' },
     { errorCode: 'ERR20092', errorMessage: 'Timeout, reversal is trying' },
     { errorCode: 'ERR20093', errorMessage: 'Violation, cannot complete(installment, loyalty)' },
     { errorCode: 'ERR20096', errorMessage: 'System malfunction' },
     { errorCode: 'ERR20098', errorMessage: 'Duplicate Reversal' },
     { errorCode: 'ERR20099', errorMessage: 'Transaction Unsuccessful' },
     { errorCode: 'ERR200YK', errorMessage: 'Card in black list.' },
     { errorCode: 'ERR200SF', errorMessage: 'Check HOSTMSG for details.' },
     { errorCode: 'ERR200GK', errorMessage: 'Foreign cards not permitted to the terminal' },
]

export default function handler(req: NextApiRequest, res: NextApiResponse) {

     if (req.method !== 'POST') {
          return res.status(405).json({ error: 'Method Not Allowed' });
     }
     console.log(req.body);

     const shouldSucceed = Math.random() < 0.5; // 50/50 chance

     if (shouldSucceed) {
          return res.status(200).json(successResponse);
     } else {
          const error = coreErrorCodes[Math.floor(Math.random() * coreErrorCodes.length)];
          return res.status(400).json({
               responseCode: error.errorCode,
               responseMsg: error.errorMessage,
          });
     }
}
